# @todo
smart_media:
    cache: apc # file, memcache
    providers:
        local:
            class: SmartCore\Bundle\MediaBundle\Provider\LocalProvider
            #directoryOriginal: '%kernel.project_dir%/usr/media_cloud'
            directoryOriginal: '%kernel.project_dir%/public/_media'
            directoryWeb: '%kernel.project_dir%/public/_media'
            webPath: '/_media'
        remote:
            class: SmartCore\Bundle\MediaBundle\Provider\RemoteProvider
            baseUrl: http://example.com
